/**
 * Central registry mapping illustration names → components.
 * The <Visual name="..."> component looks up illustrations from this map.
 */

import type { ComponentType } from "react";

// ─── Module 1 imports ──────────────────────────────────────────
import {
  M1IntroHype, M1IntroAutomation, M1IntroLlms, M1IntroDaily,
  M1AutocompleteParrot, M1HeadlinesVsReal, M1WhyHypeMatters, M1QuickCheckL1, M1KeyTakeawayL1,
  M1DishwasherVsChef, M1AutomationRealLife, M1AiRealLife, M1SortTheseOut, M1WhyMattersAutomation, M1QuickCheckL2, M1KeyTakeawayL2,
  M1WellreadParrot, M1SoundingHuman, M1MakesStuffUp, M1HowToUseIt, M1QuickCheckL3, M1KeyTakeawayL3,
  M1AiAlreadyLiving, M1WhyFeelsNew, M1AiOrNot, M1WhatMeansForYou, M1QuickCheckL4, M1KeyTakeawayL4, M1ModuleComplete,
} from "@/components/illustrations/module-1";

// ─── Module 2 imports ──────────────────────────────────────────
import {
  M2IntroConversation, M2IntroQuestions, M2IntroWrong, M2IntroTasks, M2IntroCheatsheet,
  M2ChatInterfacesIllustration, M2WhereToGoIllustration, M2FirstPromptIllustration, M2ConversationFlowIllustration, M2HiddenCapabilitiesIllustration, M2L1QuickCheckIllustration, M2L1KeyTakeawayIllustration,
  M2VaguePromptsIllustration, M2FourPillarsIllustration, M2BeforeAfterIllustration, M2ContextTrickIllustration, M2PickBetterPromptIllustration, M2TryThisNowIllustration, M2L2KeyTakeawayIllustration,
  M2HallucinationIllustration, M2AiBlundersIllustration, M2BlindSpotsIllustration, M2CatchAiIllustration, M2RightWayToThinkIllustration, M2TrustScaleIllustration, M2OneSentenceIllustration, M2L3KeyTakeawayIllustration,
  M2WritingHelpIllustration, M2ResearchHelpIllustration, M2CreativeHelpIllustration, M2StealPromptsIllustration, M2L4QuickCheckIllustration, M2L4KeyTakeawayIllustration,
  M2AiGreatAtIllustration, M2AiOkayAtIllustration, M2AiTerribleAtIllustration, M2AiVsGoogleVsHumanIllustration, M2OneRuleIllustration, M2DecisionTreeIllustration, M2L5QuickCheckIllustration, M2L5KeyTakeawayIllustration,
} from "@/components/illustrations/module-2";

// ─── Module 3 imports ──────────────────────────────────────────
import {
  M3IntroEmail, M3IntroScheduling, M3IntroLearning, M3IntroBoring,
  M3InboxOverloadIllustration, M3AiEmailPowersIllustration, M3TryItEmailIllustration, M3BeforeAfterInboxIllustration, M3InboxQuizIllustration, M3InboxTakeawayIllustration,
  M3CalendarChaosIllustration, M3SchedulingToolsIllustration, M3ProtectFreeTimeIllustration, M3GroupDinnerIllustration, M3SchedulingQuizIllustration, M3SchedulingTakeawayIllustration,
  M3PersonalTutorIllustration, M3LearnAnythingIllustration, M3CreativeProjectsIllustration, M3AdjustLevelIllustration, M3LearningQuizIllustration, M3LearningTakeawayIllustration,
  M3SummarizeDocsIllustration, M3CompareProductsIllustration, M3ConfusingPaperworkIllustration, M3WritingLettersIllustration, M3BoringQuizIllustration, M3StuffPilingUpIllustration, M3BoringTakeawayIllustration,
} from "@/components/illustrations/module-3";

// ─── Module 4 imports ──────────────────────────────────────────
import {
  M4IntroData, M4IntroFakes, M4IntroTrust, M4IntroFamily,
  DataLetterIllustration, FreeVsPaidIllustration, DataToolsIllustration, CoffeeShopStrangerIllustration, SafeToShareIllustration, QuizCheck1Illustration as M4QuizCheck1, KeyTakeaway1Illustration as M4KeyTakeaway1,
  DeepfakeFaceIllustration, GrandparentScamIllustration, RealExamplesIllustration, SpotAiContentIllustration, SomethingFeelsOffIllustration, QuizCheck2Illustration as M4QuizCheck2, KeyTakeaway2Illustration as M4KeyTakeaway2,
  LibraryBookIllustration, MedicalAiIllustration, LegalAiIllustration, FinancialAiIllustration, EmotionalAiIllustration, StartingVsFinalIllustration, SortItOutIllustration, QuizCheck3Illustration as M4QuizCheck3, KeyTakeaway3Illustration as M4KeyTakeaway3,
  ConversationWorthHavingIllustration, KidsAiIllustration, OlderAdultsAiIllustration, AgeGuidelinesIllustration, DinnerTableIllustration, AiSmartFamilyIllustration, QuizCheck4Illustration as M4QuizCheck4, KeyTakeaway4Illustration as M4KeyTakeaway4,
} from "@/components/illustrations/module-4";

// ─── Module 5 imports ──────────────────────────────────────────
import {
  M5IntroNeed, M5IntroRedflags, M5IntroBuying, M5IntroPricing,
  M5CoreDistinctionIllustration, M5DecisionFrameworkIllustration, M5SideBySideIllustration, M5HybridRealityIllustration, M5QuickCheck1Illustration, M5KeyTakeaway1Illustration,
  M5AIPitchesDifferentIllustration, M5RedFlagsIllustration, M5DemoPlaybookIllustration, M5SortSignalsIllustration, M5QuickCheck2Illustration, M5KeyTakeaway2Illustration,
  M5EvaluationsFailIllustration, M5TwelveQuestionsIllustration, M5PreBuyChecklistIllustration, M5QuickCheck3Illustration, M5KeyTakeaway3Illustration,
  M5PricingModelsIllustration, M5HybridPricingIllustration, M5TotalCostIllustration, M5BuildVsBuyIllustration, M5BuildVsBuyMatrixIllustration, M5QuickCheck4Illustration, M5KeyTakeaway4Illustration,
} from "@/components/illustrations/module-5";

// ─── Module 6 imports ──────────────────────────────────────────
import {
  M6IntroExperiment, M6IntroWeek, M6IntroMeasure, M6IntroGraduation,
  SweetSpotIllustration, BadExperimentIllustration, ExperimentIdeasIllustration, ThreeQuestionsIllustration, QuickCheck1Illustration as M6QuickCheck1, KeyTakeaway1Illustration as M6KeyTakeaway1,
  DayByDayIllustration, ExperimentLogIllustration, FixItToolkitIllustration, BeginnerMistakesIllustration, WeekOneMissionIllustration, QuickCheck2Illustration as M6QuickCheck2, KeyTakeaway2Illustration as M6KeyTakeaway2,
  ThreeQuestionsMatterIllustration, SignsWorkedIllustration, SignsDidntIllustration, WhatToDoResultsIllustration, QuickCheck3Illustration as M6QuickCheck3, KeyTakeaway3Illustration as M6KeyTakeaway3,
  WhatYouveLearnedIllustration, ThreePathsIllustration, StayingCurrentIllustration, OneThingRememberIllustration, HelpSomeoneIllustration, GraduationIllustration, KeyTakeaway4Illustration as M6KeyTakeaway4,
} from "@/components/illustrations/module-6";

// ─── Module 7 imports ──────────────────────────────────────────
import {
  M7FearStats, M7JobDisplacement, M7GenerationGap, M7ExpertVsPublic, M7TrainingSolution, M7RealVsHype, M7QuickCheck1, M7KeyTakeaway1,
  M7FailureRate, M7HypeReality, M7SevenCauses, M7McdonaldsFail, M7AirCanada, M7LawyerCase, M7AdoptionGap, M7QuickCheck2, M7KeyTakeaway2,
  M7PreferHumans, M7ChatbotHell, M7NpsGap, M7HallucinationCost, M7CantDetect, M7CustomerService, M7QuickCheck3, M7KeyTakeaway3,
  M7PrivacyShield, M7BiasScale, M7Transparency, M7YourRights, M7HealthcareAi, M7TakeControl, M7DemandBetter, M7QuickCheck4, M7KeyTakeaway4, M7ModuleComplete,
} from "@/components/illustrations/module-7";

type IllustrationComponent = ComponentType<{ className?: string }>;

export const ILLUSTRATIONS: Record<string, IllustrationComponent> = {
  // ═══ Module 1 ═══════════════════════════════════════════════
  "m1-intro-hype": M1IntroHype,
  "m1-intro-automation": M1IntroAutomation,
  "m1-intro-llms": M1IntroLlms,
  "m1-intro-daily": M1IntroDaily,
  "m1-autocomplete-parrot": M1AutocompleteParrot,
  "m1-headlines-vs-real": M1HeadlinesVsReal,
  "m1-why-hype-matters": M1WhyHypeMatters,
  "m1-quick-check-l1": M1QuickCheckL1,
  "m1-key-takeaway-l1": M1KeyTakeawayL1,
  "m1-dishwasher-vs-chef": M1DishwasherVsChef,
  "m1-automation-real-life": M1AutomationRealLife,
  "m1-ai-real-life": M1AiRealLife,
  "m1-sort-these-out": M1SortTheseOut,
  "m1-why-matters-automation": M1WhyMattersAutomation,
  "m1-quick-check-l2": M1QuickCheckL2,
  "m1-key-takeaway-l2": M1KeyTakeawayL2,
  "m1-wellread-parrot": M1WellreadParrot,
  "m1-sounding-human": M1SoundingHuman,
  "m1-makes-stuff-up": M1MakesStuffUp,
  "m1-how-to-use-it": M1HowToUseIt,
  "m1-quick-check-l3": M1QuickCheckL3,
  "m1-key-takeaway-l3": M1KeyTakeawayL3,
  "m1-ai-already-living": M1AiAlreadyLiving,
  "m1-why-feels-new": M1WhyFeelsNew,
  "m1-ai-or-not": M1AiOrNot,
  "m1-what-means-for-you": M1WhatMeansForYou,
  "m1-quick-check-l4": M1QuickCheckL4,
  "m1-key-takeaway-l4": M1KeyTakeawayL4,
  "m1-module-complete": M1ModuleComplete,

  // ═══ Module 2 ═══════════════════════════════════════════════
  "m2-intro-conversation": M2IntroConversation,
  "m2-intro-questions": M2IntroQuestions,
  "m2-intro-wrong": M2IntroWrong,
  "m2-intro-tasks": M2IntroTasks,
  "m2-intro-cheatsheet": M2IntroCheatsheet,
  "m2-chat-interfaces": M2ChatInterfacesIllustration,
  "m2-where-to-go": M2WhereToGoIllustration,
  "m2-first-prompt": M2FirstPromptIllustration,
  "m2-conversation-flow": M2ConversationFlowIllustration,
  "m2-hidden-capabilities": M2HiddenCapabilitiesIllustration,
  "m2-l1-quick-check": M2L1QuickCheckIllustration,
  "m2-l1-key-takeaway": M2L1KeyTakeawayIllustration,
  "m2-vague-prompts": M2VaguePromptsIllustration,
  "m2-four-pillars": M2FourPillarsIllustration,
  "m2-before-after": M2BeforeAfterIllustration,
  "m2-context-trick": M2ContextTrickIllustration,
  "m2-pick-better-prompt": M2PickBetterPromptIllustration,
  "m2-try-this-now": M2TryThisNowIllustration,
  "m2-l2-key-takeaway": M2L2KeyTakeawayIllustration,
  "m2-hallucination": M2HallucinationIllustration,
  "m2-ai-blunders": M2AiBlundersIllustration,
  "m2-blind-spots": M2BlindSpotsIllustration,
  "m2-catch-ai": M2CatchAiIllustration,
  "m2-right-way-to-think": M2RightWayToThinkIllustration,
  "m2-trust-scale": M2TrustScaleIllustration,
  "m2-one-sentence": M2OneSentenceIllustration,
  "m2-l3-key-takeaway": M2L3KeyTakeawayIllustration,
  "m2-writing-help": M2WritingHelpIllustration,
  "m2-research-help": M2ResearchHelpIllustration,
  "m2-creative-help": M2CreativeHelpIllustration,
  "m2-steal-prompts": M2StealPromptsIllustration,
  "m2-l4-quick-check": M2L4QuickCheckIllustration,
  "m2-l4-key-takeaway": M2L4KeyTakeawayIllustration,
  "m2-ai-great-at": M2AiGreatAtIllustration,
  "m2-ai-okay-at": M2AiOkayAtIllustration,
  "m2-ai-terrible-at": M2AiTerribleAtIllustration,
  "m2-ai-vs-google-vs-human": M2AiVsGoogleVsHumanIllustration,
  "m2-one-rule": M2OneRuleIllustration,
  "m2-decision-tree": M2DecisionTreeIllustration,
  "m2-l5-quick-check": M2L5QuickCheckIllustration,
  "m2-l5-key-takeaway": M2L5KeyTakeawayIllustration,

  // ═══ Module 3 ═══════════════════════════════════════════════
  "m3-intro-email": M3IntroEmail,
  "m3-intro-scheduling": M3IntroScheduling,
  "m3-intro-learning": M3IntroLearning,
  "m3-intro-boring": M3IntroBoring,
  "m3-inbox-overload": M3InboxOverloadIllustration,
  "m3-ai-email-powers": M3AiEmailPowersIllustration,
  "m3-try-it-email": M3TryItEmailIllustration,
  "m3-before-after-inbox": M3BeforeAfterInboxIllustration,
  "m3-inbox-quiz": M3InboxQuizIllustration,
  "m3-inbox-takeaway": M3InboxTakeawayIllustration,
  "m3-calendar-chaos": M3CalendarChaosIllustration,
  "m3-scheduling-tools": M3SchedulingToolsIllustration,
  "m3-protect-free-time": M3ProtectFreeTimeIllustration,
  "m3-group-dinner": M3GroupDinnerIllustration,
  "m3-scheduling-quiz": M3SchedulingQuizIllustration,
  "m3-scheduling-takeaway": M3SchedulingTakeawayIllustration,
  "m3-personal-tutor": M3PersonalTutorIllustration,
  "m3-learn-anything": M3LearnAnythingIllustration,
  "m3-creative-projects": M3CreativeProjectsIllustration,
  "m3-adjust-level": M3AdjustLevelIllustration,
  "m3-learning-quiz": M3LearningQuizIllustration,
  "m3-learning-takeaway": M3LearningTakeawayIllustration,
  "m3-summarize-docs": M3SummarizeDocsIllustration,
  "m3-compare-products": M3CompareProductsIllustration,
  "m3-confusing-paperwork": M3ConfusingPaperworkIllustration,
  "m3-writing-letters": M3WritingLettersIllustration,
  "m3-boring-quiz": M3BoringQuizIllustration,
  "m3-stuff-piling-up": M3StuffPilingUpIllustration,
  "m3-boring-takeaway": M3BoringTakeawayIllustration,

  // ═══ Module 4 ═══════════════════════════════════════════════
  "m4-intro-data": M4IntroData,
  "m4-intro-fakes": M4IntroFakes,
  "m4-intro-trust": M4IntroTrust,
  "m4-intro-family": M4IntroFamily,
  "m4-data-letter": DataLetterIllustration,
  "m4-free-vs-paid": FreeVsPaidIllustration,
  "m4-data-tools": DataToolsIllustration,
  "m4-coffee-shop-stranger": CoffeeShopStrangerIllustration,
  "m4-safe-to-share": SafeToShareIllustration,
  "m4-quiz-check-1": M4QuizCheck1,
  "m4-key-takeaway-1": M4KeyTakeaway1,
  "m4-deepfake-face": DeepfakeFaceIllustration,
  "m4-grandparent-scam": GrandparentScamIllustration,
  "m4-real-examples": RealExamplesIllustration,
  "m4-spot-ai-content": SpotAiContentIllustration,
  "m4-something-feels-off": SomethingFeelsOffIllustration,
  "m4-quiz-check-2": M4QuizCheck2,
  "m4-key-takeaway-2": M4KeyTakeaway2,
  "m4-library-book": LibraryBookIllustration,
  "m4-medical-ai": MedicalAiIllustration,
  "m4-legal-ai": LegalAiIllustration,
  "m4-financial-ai": FinancialAiIllustration,
  "m4-emotional-ai": EmotionalAiIllustration,
  "m4-starting-vs-final": StartingVsFinalIllustration,
  "m4-sort-it-out": SortItOutIllustration,
  "m4-quiz-check-3": M4QuizCheck3,
  "m4-key-takeaway-3": M4KeyTakeaway3,
  "m4-conversation-worth-having": ConversationWorthHavingIllustration,
  "m4-kids-ai": KidsAiIllustration,
  "m4-older-adults-ai": OlderAdultsAiIllustration,
  "m4-age-guidelines": AgeGuidelinesIllustration,
  "m4-dinner-table": DinnerTableIllustration,
  "m4-ai-smart-family": AiSmartFamilyIllustration,
  "m4-quiz-check-4": M4QuizCheck4,
  "m4-key-takeaway-4": M4KeyTakeaway4,

  // ═══ Module 5 ═══════════════════════════════════════════════
  "m5-intro-need": M5IntroNeed,
  "m5-intro-redflags": M5IntroRedflags,
  "m5-intro-buying": M5IntroBuying,
  "m5-intro-pricing": M5IntroPricing,
  "m5-core-distinction": M5CoreDistinctionIllustration,
  "m5-decision-framework": M5DecisionFrameworkIllustration,
  "m5-side-by-side": M5SideBySideIllustration,
  "m5-hybrid-reality": M5HybridRealityIllustration,
  "m5-quick-check-1": M5QuickCheck1Illustration,
  "m5-key-takeaway-1": M5KeyTakeaway1Illustration,
  "m5-ai-pitches-different": M5AIPitchesDifferentIllustration,
  "m5-red-flags": M5RedFlagsIllustration,
  "m5-demo-playbook": M5DemoPlaybookIllustration,
  "m5-sort-signals": M5SortSignalsIllustration,
  "m5-quick-check-2": M5QuickCheck2Illustration,
  "m5-key-takeaway-2": M5KeyTakeaway2Illustration,
  "m5-evaluations-fail": M5EvaluationsFailIllustration,
  "m5-twelve-questions": M5TwelveQuestionsIllustration,
  "m5-pre-buy-checklist": M5PreBuyChecklistIllustration,
  "m5-quick-check-3": M5QuickCheck3Illustration,
  "m5-key-takeaway-3": M5KeyTakeaway3Illustration,
  "m5-pricing-models": M5PricingModelsIllustration,
  "m5-hybrid-pricing": M5HybridPricingIllustration,
  "m5-total-cost": M5TotalCostIllustration,
  "m5-build-vs-buy": M5BuildVsBuyIllustration,
  "m5-build-vs-buy-matrix": M5BuildVsBuyMatrixIllustration,
  "m5-quick-check-4": M5QuickCheck4Illustration,
  "m5-key-takeaway-4": M5KeyTakeaway4Illustration,

  // ═══ Module 6 ═══════════════════════════════════════════════
  "m6-intro-experiment": M6IntroExperiment,
  "m6-intro-week": M6IntroWeek,
  "m6-intro-measure": M6IntroMeasure,
  "m6-intro-graduation": M6IntroGraduation,
  "m6-sweet-spot": SweetSpotIllustration,
  "m6-bad-experiment": BadExperimentIllustration,
  "m6-experiment-ideas": ExperimentIdeasIllustration,
  "m6-three-questions": ThreeQuestionsIllustration,
  "m6-quick-check-1": M6QuickCheck1,
  "m6-key-takeaway-1": M6KeyTakeaway1,
  "m6-day-by-day": DayByDayIllustration,
  "m6-experiment-log": ExperimentLogIllustration,
  "m6-fix-it-toolkit": FixItToolkitIllustration,
  "m6-beginner-mistakes": BeginnerMistakesIllustration,
  "m6-week-one-mission": WeekOneMissionIllustration,
  "m6-quick-check-2": M6QuickCheck2,
  "m6-key-takeaway-2": M6KeyTakeaway2,
  "m6-three-questions-matter": ThreeQuestionsMatterIllustration,
  "m6-signs-worked": SignsWorkedIllustration,
  "m6-signs-didnt": SignsDidntIllustration,
  "m6-what-to-do-results": WhatToDoResultsIllustration,
  "m6-quick-check-3": M6QuickCheck3,
  "m6-key-takeaway-3": M6KeyTakeaway3,
  "m6-what-youve-learned": WhatYouveLearnedIllustration,
  "m6-three-paths": ThreePathsIllustration,
  "m6-staying-current": StayingCurrentIllustration,
  "m6-one-thing-remember": OneThingRememberIllustration,
  "m6-help-someone": HelpSomeoneIllustration,
  "m6-graduation": GraduationIllustration,
  "m6-key-takeaway-4": M6KeyTakeaway4,

  // ═══ Module 7 ═══════════════════════════════════════════════
  "m7-fear-stats": M7FearStats,
  "m7-job-displacement": M7JobDisplacement,
  "m7-generation-gap": M7GenerationGap,
  "m7-expert-vs-public": M7ExpertVsPublic,
  "m7-training-solution": M7TrainingSolution,
  "m7-real-vs-hype": M7RealVsHype,
  "m7-quick-check-1": M7QuickCheck1,
  "m7-key-takeaway-1": M7KeyTakeaway1,
  "m7-failure-rate": M7FailureRate,
  "m7-hype-reality": M7HypeReality,
  "m7-seven-causes": M7SevenCauses,
  "m7-mcdonalds-fail": M7McdonaldsFail,
  "m7-air-canada": M7AirCanada,
  "m7-lawyer-case": M7LawyerCase,
  "m7-adoption-gap": M7AdoptionGap,
  "m7-quick-check-2": M7QuickCheck2,
  "m7-key-takeaway-2": M7KeyTakeaway2,
  "m7-prefer-humans": M7PreferHumans,
  "m7-chatbot-hell": M7ChatbotHell,
  "m7-nps-gap": M7NpsGap,
  "m7-hallucination-cost": M7HallucinationCost,
  "m7-cant-detect": M7CantDetect,
  "m7-customer-service": M7CustomerService,
  "m7-quick-check-3": M7QuickCheck3,
  "m7-key-takeaway-3": M7KeyTakeaway3,
  "m7-privacy-shield": M7PrivacyShield,
  "m7-bias-scale": M7BiasScale,
  "m7-transparency": M7Transparency,
  "m7-your-rights": M7YourRights,
  "m7-healthcare-ai": M7HealthcareAi,
  "m7-take-control": M7TakeControl,
  "m7-demand-better": M7DemandBetter,
  "m7-quick-check-4": M7QuickCheck4,
  "m7-key-takeaway-4": M7KeyTakeaway4,
  "m7-module-complete": M7ModuleComplete,
};

export type IllustrationName = keyof typeof ILLUSTRATIONS;
